# app/schemas/valuation.py

from datetime import datetime
from uuid import UUID

from pydantic import BaseModel, ConfigDict, Field

from app.schemas.admin import ValuationAiResponseBlob, ValuationJsonBlob, ValuationReportContextBlob


class ValuationResponse(BaseModel):
    id: UUID = Field(..., description="Database UUID for the stored valuation report.")
    valuation_id: str = Field(
        ...,
        description="Public valuation reference generated by the system.",
    )
    user_id: UUID = Field(..., description="Owner user UUID.")
    category: str = Field(
        ...,
        description="Valuation category, currently derived from the submitted property type.",
    )
    country_code: str = Field(..., description="Detected property country code.")
    subscription_id: UUID = Field(..., description="Subscription used to generate the valuation.")
    created_at: datetime = Field(..., description="UTC timestamp when the valuation report was created.")

    model_config = ConfigDict(
        from_attributes=True,
        json_schema_extra={
            "example": {
                "id": "b1115df4-038f-4cea-9d39-a09d16138801",
                "valuation_id": "DV-20260325-0001",
                "user_id": "97d39a40-6cf6-4f8a-8a7e-0b33778c44bb",
                "category": "apartment",
                "country_code": "AE",
                "subscription_id": "f42c8032-6e4e-4c8c-8d16-31fbe8d0678f",
                "created_at": "2026-03-25T14:05:33.000000Z",
            }
        },
    )


class ValuationDetailResponse(ValuationResponse):
    user_fields: ValuationJsonBlob = Field(
        ...,
        description="Original user-submitted valuation input stored with the report.",
    )
    ai_response: ValuationAiResponseBlob = Field(
        ...,
        description="AI-generated valuation output saved for the report.",
    )
    report_context: ValuationReportContextBlob = Field(
        ...,
        description="Normalized context used to build the rendered report.",
    )

    model_config = ConfigDict(
        from_attributes=True,
        json_schema_extra={
            "example": {
                "id": "b1115df4-038f-4cea-9d39-a09d16138801",
                "valuation_id": "DV-20260325-0001",
                "user_id": "97d39a40-6cf6-4f8a-8a7e-0b33778c44bb",
                "category": "apartment",
                "country_code": "AE",
                "subscription_id": "f42c8032-6e4e-4c8c-8d16-31fbe8d0678f",
                "created_at": "2026-03-25T14:05:33.000000Z",
                "user_fields": {
                    "country": "United Arab Emirates",
                    "full_address": "Yas Island, Abu Dhabi, UAE",
                    "property_type": "apartment",
                    "built_up_area": "1250 sqft",
                    "full_name": "John Doe",
                    "email": "john@example.com",
                },
                "ai_response": {
                    "property_details": {
                        "address": "Yas Island, Abu Dhabi, UAE",
                        "property_type": "apartment",
                    },
                    "final_value_opinion": {
                        "market_value": 1850000,
                        "currency": "AED",
                    },
                    "forecast": None,
                },
                "report_context": {
                    "currency_code": "AED",
                    "future_outlook": [],
                    "property_maps": {"static_map_url": "https://maps.example/static-map"},
                },
            }
        },
    )
