"""create initial schema

Revision ID: 04811d707da2
Revises: 
Create Date: 2026-03-26 11:14:51.492336

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '04811d707da2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(sa.text("CREATE SEQUENCE IF NOT EXISTS valuation_seq START WITH 1 INCREMENT BY 1"))
    op.create_table('countries',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('country_code', sa.String(), nullable=True),
    sa.Column('dial_code', sa.String(), nullable=True),
    sa.Column('currency_code', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('country_code', name='uq_country_country_code'),
    sa.UniqueConstraint('name', name='uq_country_name')
    )
    op.create_index(op.f('ix_countries_country_code'), 'countries', ['country_code'], unique=True)
    op.create_index(op.f('ix_countries_dial_code'), 'countries', ['dial_code'], unique=False)
    op.create_index(op.f('ix_countries_id'), 'countries', ['id'], unique=False)
    op.create_table('exchange_rates',
    sa.Column('currency_code', sa.String(length=3), nullable=False),
    sa.Column('rate_to_usd', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('currency_code')
    )
    op.create_index(op.f('ix_exchange_rates_id'), 'exchange_rates', ['id'], unique=False)
    op.create_table('inquiries',
    sa.Column('type', sa.Enum('CONTACT', 'SERVICE', name='inquiry_type'), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('phone_number', sa.String(), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('services', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inquiries_id'), 'inquiries', ['id'], unique=False)
    op.create_table('subscription_plans',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('country_code', sa.String(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('max_reports', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'country_code', 'price', 'currency', 'max_reports', name='uq_subscription_plan_unique')
    )
    op.create_index('ix_subscription_plans_country_active', 'subscription_plans', ['country_code', 'is_active'], unique=False)
    op.create_index(op.f('ix_subscription_plans_country_code'), 'subscription_plans', ['country_code'], unique=False)
    op.create_index(op.f('ix_subscription_plans_id'), 'subscription_plans', ['id'], unique=False)
    op.create_table('subscription_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subscription_duration_days', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('system_config',
    sa.Column('config_key', sa.String(length=150), nullable=False),
    sa.Column('config_value', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('config_key', name='uq_system_config_key')
    )
    op.create_index(op.f('ix_system_config_config_key'), 'system_config', ['config_key'], unique=True)
    op.create_index(op.f('ix_system_config_id'), 'system_config', ['id'], unique=False)
    op.create_table('users',
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('mobile_number', sa.String(), nullable=False),
    sa.Column('country_id', sa.UUID(), nullable=True),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('provider', sa.String(), nullable=True),
    sa.Column('provider_id', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_email_verified', sa.Boolean(), nullable=True),
    sa.Column('email_verified_at', sa.DateTime(), nullable=True),
    sa.Column('is_superuser', sa.Boolean(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['country_id'], ['countries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_email_verified_at'), 'users', ['email_verified_at'], unique=False)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_mobile_number'), 'users', ['mobile_number'], unique=True)
    op.create_index(op.f('ix_users_provider_id'), 'users', ['provider_id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=False)
    op.create_table('email_verification_tokens',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('used', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_email_verification_tokens_id'), 'email_verification_tokens', ['id'], unique=False)
    op.create_table('feedback',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.Enum('GENERAL', 'VALUATION', 'PAYMENT', 'SUBSCRIPTION', name='feedback_type'), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('valuation_id', sa.String(), nullable=True),
    sa.Column('subscription_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('OPEN', 'IN_PROGRESS', 'RESOLVED', 'CLOSED', name='feedback_status'), nullable=True),
    sa.Column('admin_note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_feedback_created_at'), 'feedback', ['created_at'], unique=False)
    op.create_index(op.f('ix_feedback_id'), 'feedback', ['id'], unique=False)
    op.create_index(op.f('ix_feedback_status'), 'feedback', ['status'], unique=False)
    op.create_index('ix_feedback_status_created_at', 'feedback', ['status', 'created_at'], unique=False)
    op.create_index(op.f('ix_feedback_subscription_id'), 'feedback', ['subscription_id'], unique=False)
    op.create_index('ix_feedback_user_created_at', 'feedback', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_feedback_user_id'), 'feedback', ['user_id'], unique=False)
    op.create_index(op.f('ix_feedback_valuation_id'), 'feedback', ['valuation_id'], unique=False)
    op.create_table('password_reset_tokens',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('used', sa.Boolean(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_password_reset_tokens_id'), 'password_reset_tokens', ['id'], unique=False)
    op.create_table('refresh_tokens',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('revoked', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_refresh_tokens_id'), 'refresh_tokens', ['id'], unique=False)
    op.create_table('staff',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('can_access_user', sa.Boolean(), nullable=True),
    sa.Column('can_access_staff', sa.Boolean(), nullable=True),
    sa.Column('can_access_dashboard', sa.Boolean(), nullable=True),
    sa.Column('can_access_reports', sa.Boolean(), nullable=True),
    sa.Column('can_access_subscriptions_plans', sa.Boolean(), nullable=True),
    sa.Column('can_access_config', sa.Boolean(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('user_subscriptions',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('plan_id', sa.UUID(), nullable=False),
    sa.Column('pricing_country_code', sa.String(), nullable=False),
    sa.Column('ip_country_code', sa.String(), nullable=True),
    sa.Column('payment_country_code', sa.String(), nullable=True),
    sa.Column('razorpay_order_id', sa.String(), nullable=True),
    sa.Column('razorpay_payment_id', sa.String(), nullable=True),
    sa.Column('razorpay_signature', sa.String(), nullable=True),
    sa.Column('payment_status', sa.String(), nullable=True),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reports_used', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_expired', sa.Boolean(), nullable=True),
    sa.Column('auto_renew', sa.Boolean(), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['subscription_plans.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_user_subscriptions_active_expiry_window', 'user_subscriptions', ['is_active', 'is_expired', 'end_date'], unique=False)
    op.create_index('ix_user_subscriptions_end_date', 'user_subscriptions', ['end_date'], unique=False)
    op.create_index(op.f('ix_user_subscriptions_id'), 'user_subscriptions', ['id'], unique=False)
    op.create_index(op.f('ix_user_subscriptions_ip_country_code'), 'user_subscriptions', ['ip_country_code'], unique=False)
    op.create_index(op.f('ix_user_subscriptions_payment_country_code'), 'user_subscriptions', ['payment_country_code'], unique=False)
    op.create_index('ix_user_subscriptions_payment_status', 'user_subscriptions', ['payment_status'], unique=False)
    op.create_index(op.f('ix_user_subscriptions_plan_id'), 'user_subscriptions', ['plan_id'], unique=False)
    op.create_index('ix_user_subscriptions_pricing_country_code', 'user_subscriptions', ['pricing_country_code'], unique=False)
    op.create_index('ix_user_subscriptions_start_date', 'user_subscriptions', ['start_date'], unique=False)
    op.create_index('ix_user_subscriptions_user_active_window', 'user_subscriptions', ['user_id', 'is_active', 'is_expired', 'start_date', 'end_date'], unique=False)
    op.create_index(op.f('ix_user_subscriptions_user_id'), 'user_subscriptions', ['user_id'], unique=False)
    op.create_table('valuation_jobs',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('subscription_id', sa.UUID(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('country_code', sa.String(length=5), nullable=False),
    sa.Column('request_payload', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('valuation_id', sa.String(), nullable=True),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_valuation_jobs_country_code'), 'valuation_jobs', ['country_code'], unique=False)
    op.create_index(op.f('ix_valuation_jobs_created_at'), 'valuation_jobs', ['created_at'], unique=False)
    op.create_index(op.f('ix_valuation_jobs_id'), 'valuation_jobs', ['id'], unique=False)
    op.create_index(op.f('ix_valuation_jobs_status'), 'valuation_jobs', ['status'], unique=False)
    op.create_index('ix_valuation_jobs_status_created_at', 'valuation_jobs', ['status', 'created_at'], unique=False)
    op.create_index(op.f('ix_valuation_jobs_subscription_id'), 'valuation_jobs', ['subscription_id'], unique=False)
    op.create_index('ix_valuation_jobs_user_created_at', 'valuation_jobs', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_valuation_jobs_user_id'), 'valuation_jobs', ['user_id'], unique=False)
    op.create_index(op.f('ix_valuation_jobs_valuation_id'), 'valuation_jobs', ['valuation_id'], unique=False)
    op.create_table('feedback_messages',
    sa.Column('feedback_id', sa.UUID(), nullable=False),
    sa.Column('sender', sa.Enum('USER', 'ADMIN', name='feedback_sender'), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['feedback_id'], ['feedback.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_feedback_messages_id'), 'feedback_messages', ['id'], unique=False)
    op.create_table('valuation_reports',
    sa.Column('valuation_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('country_code', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('user_fields', sa.JSON(), nullable=False),
    sa.Column('ai_response', sa.JSON(), nullable=False),
    sa.Column('subscription_id', sa.UUID(), nullable=False),
    sa.Column('report_context', sa.JSON(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['subscription_id'], ['user_subscriptions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_valuation_reports_category'), 'valuation_reports', ['category'], unique=False)
    op.create_index(op.f('ix_valuation_reports_country_code'), 'valuation_reports', ['country_code'], unique=False)
    op.create_index('ix_valuation_reports_country_created_at', 'valuation_reports', ['country_code', 'created_at'], unique=False)
    op.create_index(op.f('ix_valuation_reports_created_at'), 'valuation_reports', ['created_at'], unique=False)
    op.create_index(op.f('ix_valuation_reports_id'), 'valuation_reports', ['id'], unique=False)
    op.create_index(op.f('ix_valuation_reports_subscription_id'), 'valuation_reports', ['subscription_id'], unique=False)
    op.create_index('ix_valuation_reports_user_created_at', 'valuation_reports', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_valuation_reports_user_id'), 'valuation_reports', ['user_id'], unique=False)
    op.create_index(op.f('ix_valuation_reports_valuation_id'), 'valuation_reports', ['valuation_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_valuation_reports_valuation_id'), table_name='valuation_reports')
    op.drop_index(op.f('ix_valuation_reports_user_id'), table_name='valuation_reports')
    op.drop_index('ix_valuation_reports_user_created_at', table_name='valuation_reports')
    op.drop_index(op.f('ix_valuation_reports_subscription_id'), table_name='valuation_reports')
    op.drop_index(op.f('ix_valuation_reports_id'), table_name='valuation_reports')
    op.drop_index(op.f('ix_valuation_reports_created_at'), table_name='valuation_reports')
    op.drop_index('ix_valuation_reports_country_created_at', table_name='valuation_reports')
    op.drop_index(op.f('ix_valuation_reports_country_code'), table_name='valuation_reports')
    op.drop_index(op.f('ix_valuation_reports_category'), table_name='valuation_reports')
    op.drop_table('valuation_reports')
    op.drop_index(op.f('ix_feedback_messages_id'), table_name='feedback_messages')
    op.drop_table('feedback_messages')
    op.drop_index(op.f('ix_valuation_jobs_valuation_id'), table_name='valuation_jobs')
    op.drop_index(op.f('ix_valuation_jobs_user_id'), table_name='valuation_jobs')
    op.drop_index('ix_valuation_jobs_user_created_at', table_name='valuation_jobs')
    op.drop_index(op.f('ix_valuation_jobs_subscription_id'), table_name='valuation_jobs')
    op.drop_index('ix_valuation_jobs_status_created_at', table_name='valuation_jobs')
    op.drop_index(op.f('ix_valuation_jobs_status'), table_name='valuation_jobs')
    op.drop_index(op.f('ix_valuation_jobs_id'), table_name='valuation_jobs')
    op.drop_index(op.f('ix_valuation_jobs_created_at'), table_name='valuation_jobs')
    op.drop_index(op.f('ix_valuation_jobs_country_code'), table_name='valuation_jobs')
    op.drop_table('valuation_jobs')
    op.drop_index(op.f('ix_user_subscriptions_user_id'), table_name='user_subscriptions')
    op.drop_index('ix_user_subscriptions_user_active_window', table_name='user_subscriptions')
    op.drop_index('ix_user_subscriptions_start_date', table_name='user_subscriptions')
    op.drop_index('ix_user_subscriptions_pricing_country_code', table_name='user_subscriptions')
    op.drop_index(op.f('ix_user_subscriptions_plan_id'), table_name='user_subscriptions')
    op.drop_index('ix_user_subscriptions_payment_status', table_name='user_subscriptions')
    op.drop_index(op.f('ix_user_subscriptions_payment_country_code'), table_name='user_subscriptions')
    op.drop_index(op.f('ix_user_subscriptions_ip_country_code'), table_name='user_subscriptions')
    op.drop_index(op.f('ix_user_subscriptions_id'), table_name='user_subscriptions')
    op.drop_index('ix_user_subscriptions_end_date', table_name='user_subscriptions')
    op.drop_index('ix_user_subscriptions_active_expiry_window', table_name='user_subscriptions')
    op.drop_table('user_subscriptions')
    op.drop_table('staff')
    op.drop_index(op.f('ix_refresh_tokens_id'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index(op.f('ix_password_reset_tokens_id'), table_name='password_reset_tokens')
    op.drop_table('password_reset_tokens')
    op.drop_index(op.f('ix_feedback_valuation_id'), table_name='feedback')
    op.drop_index(op.f('ix_feedback_user_id'), table_name='feedback')
    op.drop_index('ix_feedback_user_created_at', table_name='feedback')
    op.drop_index(op.f('ix_feedback_subscription_id'), table_name='feedback')
    op.drop_index('ix_feedback_status_created_at', table_name='feedback')
    op.drop_index(op.f('ix_feedback_status'), table_name='feedback')
    op.drop_index(op.f('ix_feedback_id'), table_name='feedback')
    op.drop_index(op.f('ix_feedback_created_at'), table_name='feedback')
    op.drop_table('feedback')
    op.drop_index(op.f('ix_email_verification_tokens_id'), table_name='email_verification_tokens')
    op.drop_table('email_verification_tokens')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_provider_id'), table_name='users')
    op.drop_index(op.f('ix_users_mobile_number'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email_verified_at'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_system_config_id'), table_name='system_config')
    op.drop_index(op.f('ix_system_config_config_key'), table_name='system_config')
    op.drop_table('system_config')
    op.drop_table('subscription_settings')
    op.drop_index(op.f('ix_subscription_plans_id'), table_name='subscription_plans')
    op.drop_index(op.f('ix_subscription_plans_country_code'), table_name='subscription_plans')
    op.drop_index('ix_subscription_plans_country_active', table_name='subscription_plans')
    op.drop_table('subscription_plans')
    op.drop_index(op.f('ix_inquiries_id'), table_name='inquiries')
    op.drop_table('inquiries')
    op.drop_index(op.f('ix_exchange_rates_id'), table_name='exchange_rates')
    op.drop_table('exchange_rates')
    op.execute("DROP SEQUENCE IF EXISTS valuation_seq")
    op.drop_index(op.f('ix_countries_id'), table_name='countries')
    op.drop_index(op.f('ix_countries_dial_code'), table_name='countries')
    op.drop_index(op.f('ix_countries_country_code'), table_name='countries')
    op.drop_table('countries')
    # ### end Alembic commands ###
