"""add_unified_payment_columns

Revision ID: 2c76f08c5159
Revises: 04811d707da2
Create Date: 2026-05-21 10:18:41.234243

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2c76f08c5159"
down_revision: Union[str, Sequence[str], None] = "04811d707da2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user_subscriptions", sa.Column("payment_provider", sa.String(), nullable=True))
    op.add_column("user_subscriptions", sa.Column("provider_order_id", sa.String(), nullable=True))
    op.add_column("user_subscriptions", sa.Column("provider_payment_id", sa.String(), nullable=True))
    op.add_column("user_subscriptions", sa.Column("provider_signature", sa.String(), nullable=True))
    op.create_index(
        op.f("ix_user_subscriptions_payment_provider"), "user_subscriptions", ["payment_provider"], unique=False
    )
    op.create_index(
        op.f("ix_user_subscriptions_provider_order_id"), "user_subscriptions", ["provider_order_id"], unique=False
    )
    op.create_index(
        op.f("ix_user_subscriptions_provider_payment_id"), "user_subscriptions", ["provider_payment_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_user_subscriptions_provider_payment_id"), table_name="user_subscriptions")
    op.drop_index(op.f("ix_user_subscriptions_provider_order_id"), table_name="user_subscriptions")
    op.drop_index(op.f("ix_user_subscriptions_payment_provider"), table_name="user_subscriptions")
    op.drop_column("user_subscriptions", "provider_signature")
    op.drop_column("user_subscriptions", "provider_payment_id")
    op.drop_column("user_subscriptions", "provider_order_id")
    op.drop_column("user_subscriptions", "payment_provider")
    # ### end Alembic commands ###
