"""remove is secret from system config table

Revision ID: 6de94e144773
Revises: 685d1e0a8109
Create Date: 2026-03-11 16:24:12.207030

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6de94e144773'
down_revision: Union[str, Sequence[str], None] = '685d1e0a8109'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('system_config_config_key_key'), 'system_config', type_='unique')
    op.create_index(op.f('ix_system_config_config_key'), 'system_config', ['config_key'], unique=True)
    op.create_index(op.f('ix_system_config_id'), 'system_config', ['id'], unique=False)
    op.create_unique_constraint('uq_system_config_key', 'system_config', ['config_key'])
    op.drop_column('system_config', 'is_secret')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('system_config', sa.Column('is_secret', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True))
    op.drop_constraint('uq_system_config_key', 'system_config', type_='unique')
    op.drop_index(op.f('ix_system_config_id'), table_name='system_config')
    op.drop_index(op.f('ix_system_config_config_key'), table_name='system_config')
    op.create_unique_constraint(op.f('system_config_config_key_key'), 'system_config', ['config_key'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
